### model
model_name_or_path: google/gemma-3-4b-it
template: gemma3-pawa

### export
# export_dir: outputs/pawa-zulu-pt/checkpoint-3500
export_dir: outputs/test_output
export_size: 5
export_device: cpu # choices: [cpu, auto]
export_legacy_format: false
