### model
model_name_or_path: google/gemma-3-4b-it
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full
# lora_rank: 64
# lora_target: all
# lora_dropout: 0.0
# flash_attn: auto

### dataset
dataset_dir: data
dataset: aya-zulu-pretrained
template: gemma3-pawa
cutoff_len: 1024
# max_samples: 1e5
overwrite_cache: true
# preprocessing_num_workers: 16 # incompatible with streaming
dataloader_num_workers: 8
streaming: true
max_steps: 1787219
packing: true

### output
output_dir: outputs/pawa-zulu-pt
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 2
lr_scheduler_type: cosine
max_grad_norm: 1.0
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
