### model
# model_name_or_path: google/gemma-3-4b-it
# model_name_or_path: google/gemma-3-1b-pt
model_name_or_path: google/gemma-3-270m
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full
# lora_rank: 64
# lora_target: all
# lora_alpha:
# lora_dropout: 0.0
# flash_attn: auto

### dataset
dataset_dir: data
dataset: aya-zulu-pretrained
template: gemma3-pawa
cutoff_len: 1024
# max_samples: 1e5
overwrite_cache: true
# preprocessing_num_workers: 16 # incompatible with streaming
dataloader_num_workers: 8
streaming: true

max_steps: 787219
packing: true

### output
output_dir: outputs/pawa-270m-zulu-pt
logging_steps: 20
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb # choices: [none, wandb, tensorboard, swanlab, mlflow]
save_total_limit: 2

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 2
lr_scheduler_type: cosine
max_grad_norm: 1.0
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
# resume_from_checkpoint: outputs/pawa-zulu-pt/checkpoint-3500
resume_from_checkpoint: null
#
